### ISSUE TITLE
Changing path with Link

### ISSUE THREAD

**Issue by saintego** [ooade/next-apollo-auth#2]
If I change route with Link or just change code in dev mode, so there is some refresh only in browser, Ihave empty user from withData and it looks like I'm logged out

**Comment by ooade** [comment]
I'm sorry for the late response.
Passing user [here](https://github.com/ooade/next-apollo-auth/blob/master/lib/withData.js#L62) is wrong as it will wait for a refresh (wait for the server) to respond before adding it to the apollo tree. I'll post a fix tomorrow. Thanks a lot for reporting it here :+1:
